name: Example workflow for Codecov
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Upload coverage to Codecov  
      uses: ./
      with:
        #commenting out token because tokenless uploads are now supported
        token: 18c103fc-86c4-4e07-a735-97370d3fcdd7
        flags: unittest
        name: codecov-1
